version: "3.9"

services:
  db:
    container_name: zzolab_db
    image: mysql
    env_file: ./backend/.prod.env
    volumes:
      - zzolab_db_data:/var/lib/mysql
    networks:
      - backend-network

  backend:
    container_name: zzolab_back
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/zzolab:backend-${GITHUB_SHA}
    pull_policy: always
    command: /scripts/prod_start.sh
    volumes:
      - ./backend:/app
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - db
    env_file: ./backend/.prod.env
    networks:
      - nginx-network
      - backend-network

  nginx:
    container_name: zzolab_nginx
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/zzolab:nginx-${GITHUB_SHA}
    pull_policy: always
    ports:
      - 80:80
    volumes:
      - ./nginx/prod.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/static
    depends_on:
      - backend
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge
  backend-network:
    driver: bridge

volumes:
  zzolab_db_data:
  static_volume:
  media_volume:
